### ISSUE TITLE
Disable checkpoint?

### ISSUE THREAD

**Issue by leepc12** [pcingola/BigDataScript#100]
I share bds scripts with my colleagues, they are producing a lot of checkpoint files (*.chp) on my bds script folder.

I don't actually use checkpoint feature. Is it possible to disable automatic checkpointing or generate chp files on working directory?

**Comment by leepc12** [comment]
I modified the code myself. Thanks,

**Comment by pcingola** [comment]
Hi, sorry for the long delay answering, I was out of town.
If you'd like to share your code, please send a PR and I'll be glad to merge it.

Another comment: Under normal circumstances, bds should not create checkpoints (that is, assuming that most of the times the script executes OK), since checkpoints are created on error conditions.
Furthermore, checkpoints can be helpful to debug your code (using 'bds -i file.chp').
