### ISSUE TITLE
par function() return value

### ISSUE THREAD

**Issue by leepc12** [pcingola/BigDataScript#113]
Hello, BDS is amazing. I finished ENCODE chipseq pipeline https://github.com/kundajelab/ENCODE_chipseq_pipeline) with it and it's working quite good.

But there is one limitation for BDS... which is really important for my project.

Could you make 'par2' which returns function value instead of PID?

In the following example, # of replicates (num_rep) can vary so I cannot use par { } block to get return value.

My adhoc remedy for this problem is save return value to temporary file. But it's really ugly...

```
main() {

	string[] tagaligns

	for(int i=0; i< rep_num ;i++) {
		fastq := get_fastq( i )
		tagalign := par2 align( fastq )
		tagaligns.add( tagalign )
	}

	wait

	generate_signal( tagaligns )	
}

string align() {
	bam := bwa()
	wait
	filt_bam := filter( bam )

	return bam_to_tagalign( filt_bam )
}
...
```

**Comment by pcingola** [comment]
Hi Jin,
  The problem is that at the time the function is called, i.e. 'par2 align(...)' in 
your example, the results is not known, thus the program cannot assign 
the value to 'tagalign'. The only way to know the result would be to wait 
until the invocation to align(..) finishes. This would defeat the purpose 
of running in parallel, since we have to wait until the execution finishes 
anyway.
   Let me know if I misinterpreted what you meant, but I think that what 
you are asking for would not work.

**Comment by leepc12** [comment]
Thanks for the explanation!, that completely makes sense.

How about tracking and getting return value from PID at wait?

return_value := wait PID

```
main() {

    string{} tagaligns
    int{} pid_map

    for(int i=0; i< rep_num ;i++) {
        fastq := get_fastq( i )
        pid_map[ "$i" ] = par align( fastq )
    }

    // if PID is from par function(), wait returns function return value  
    for(int i=0; i< rep_num ;i++) {
       tagaligns[ "$i" ] = wait pid_map[ "$i" ] )
    }

   // convert tagaligns map to array somewhere here 

    generate_signal( tagaligns_array )
}

string align() {
    bam := bwa()
    wait
    filt_bam := filter( bam )

    return bam_to_tagalign( filt_bam )
}
```

**Comment by leepc12** [comment]
For `par` function, I decided to use global variables instead of function return to save output filenames.
