### ISSUE TITLE
there is something unexpected $var expand in sys command

### ISSUE THREAD

**Issue by zengfengbo** [pcingola/BigDataScript#117]
## bds scripts
$ cat dollar_expand_error.bds
task {
  sys cat ~/.bashrc | ruby -lane 'puts **$F**.size'
}

## $F is the inner global var which will recognized by ruby.
$ cat ~/.bashrc | ruby -lane 'puts **$F**.size' |head -2
2
0

## unexpected error
$ bds dollar_expand_error.bds
Compiler messages:
ERROR [ file 'dollar_expand_error.bds', line 2 ] :	Symbol 'F' cannot be resolved

Compiler messages:
ERROR [ file 'dollar_expand_error.bds', line 2 ] :	Symbol 'F' cannot be resolved

**Comment by pcingola** [comment]
It should work OK now as long as you escape the variable name (otherwise it 
gets interpreted by bds, as it should be). So your sys line should be:

    sys cat ~/.bashrc | ruby -lane 'puts $\F.size'

Notice the backslash before 'F'.

Example:
    #!/usr/bin/env bds

    task perl -e 'print "PID:$$\n";'
    task perl -e 'use English; print "PID:\$PID\n";'
    task perl -e 'use English; print "REAL_USER_ID:\$REAL_USER_ID\n";'

When you run it you get the variables escaped to perl:

    $ ./z.bds
    PID:3665'
    PID:3664
    REAL_USER_ID:501
   
In this case '$$', '$PID' and '$REAL_USER_ID' are interpreted 
by perl, as expected.
