### ISSUE TITLE
try / finally non-standard behavior

### ISSUE THREAD

**Issue by aleksandergurin** [pcingola/BigDataScript#186]
## Problem
`finally` clause does not executed in some cases.

## Steps to reproduce
```
try {
    error('Testing error')
} finally {
    println 'Finally clause'
}
```

## Result
String `"Finally clause"` won't be printed.

## Expected behavior
As in most languages, developer would expect such semantics that execute `finally` clause _always_ (even when process exit with unexpected error).
Example from python:
```python
try:
    exit(1)
finally:
    print('Finally clause')
```
That code results in `"Finally clause"` will be printed in console.

**Comment by pcingola** [comment]
Although I didn't do exhaustive research on the topic, I'd be hesitant to say _"most of the languages"_ or _"developer would expect"_.

This is clearly and language-dependent. For instance, in **Python** the 'exit()' command doesn't actually exit the program, it just raises a `SystemExit` exception (https://docs.python.org/2/library/sys.html)

In contrast, Java's `System.exit()` does actually exit the program, so if you execute the following code:
```
public class Zzz {
	public static void main(String[] args) {
		try {
			System.out.println("try");
			System.exit(0);
		} finally System.out.println("finally");
	}
```

the output is just:
```
try
```
because the `System.exit` is honored and the `finally` block is never executed.

Expecting whether `exit` or `finally` should be honored is ambiguous, since both are right and wrong at the same time....it's a gray area.
