### ISSUE TITLE
Empty STDOUT when executing cluster stat command 'qstat (with SGE)

### ISSUE THREAD

**Issue by golharam** [pcingola/BigDataScript#68]
Does this warning message mean anything important?  SGE clears a job from qstat right when it ends, so if the job isn't listed, its completed (either succesfully or failed).  When this warning appears from BDS, what does it mean for the pipeline it ran?   Is the task considered finished?  I see a missing count, but haven't looked to see what is done with this.

**Comment by pcingola** [comment]
In a busy cluster there are usually thousands of jobs either running or 
queued, so having an empty STDOUT does not usually happen (it may 
indicate an error when running qstat, rather than a normal condition).

If the cluster is only running one job, and qstat command doesn't 
print anything (not even a header line) when the cluster has no jobs 
running / queued, then it's a normal condition and you can safely ignore it.

May be I should only print this message when running in verbose mode...

**Comment by golharam** [comment]
As long as it doesn't effect the pipeline, I think an empty queue is fine.
Our cluster has a handful of users and most of the time, I"m the only one
running jobs with SGE anyway.

**Comment by pcingola** [comment]
Done. Now the message is shown only when verbose mode is set.
