### ISSUE TITLE
task hint for ". /etc/profile.d/modules.sh;"

### ISSUE THREAD

**Issue by leepc12** [pcingola/BigDataScript#78]
Hello,

I am adding my modules and environmental variable by using ". /etc/profile.d/modules.sh;"

```
task {
	sys . /etc/profile.d/modules.sh; module add bedtools/2.18.0;
	sys echo something
}
```
Could you remove any command line starting with ". /etc/profile.d/modules.sh" from task hint? Now I cannot 

```
00:11:12.287    ExecutionerClusterSge 'ClusterSge[13]': Tasks [ClusterSge[13]]          Pending : 0     Running: 6      Done: 0
                | PID    | Task state        | Task name   | Dependencies | Task definition                                                                                                                                        | 
                | ------ | ----------------- | ----------- | ------------ | ------------------------------------------------------------------------------------------------------------------------------------------------------ | 
                | 136871 | running (RUNNING) | bwa aln PE2 |              |  . /etc/profile.d/modules.sh; module add bedtools/2.18.0; module add bowtie/2.0.5; module add bwa/0.7.7; export PATH="/home/leepc12/devtools/dx-toolki | 
```
How can I define job name? It's always STDIN and I want to change it.
```
job-ID  prior   name       user         state submit/start at     queue                          slots ja-task-ID 
-----------------------------------------------------------------------------------------------------------------
 140556 0.00000 STDIN      leepc12      qw    03/12/2015 22:21:07                                    4        
```

**Comment by leepc12** [comment]
1) passing environment vars to BDS jobs

Hello, I found that all environment variables of bash shell are passed to BDS jobs even without "clusterRunAdditionalArgs = -V" in bds.config.

Qsubbing bash script without BDS does not pass environment variables if -V is not specified as argument. So many people control versions of programs by adding "module add MODULE_NAME" or "export PATH=$PATH:PROGRAM_PATH" on top of their bash script.

I think BDS should not pass environment variables by default.


2) how to add module or define PATH?

```
task ( cpus := 16 )  {
    sys . /etc/profile.d/modules.sh; module add bedtools/2.18.0;
    sys echo something
}
```

The above code is how I add modules or PATH to BDS jobs. The problem is that the first sys command takes 16 cpus! which is definitely not expected.

We need something like the following:


```
$PRELOAD = ". /etc/profile.d/modules.sh; module add bedtools/2.18.0;"
task ( cpus := 16, preload := $PRELOAD )  {
    //sys . /etc/profile.d/modules.sh; module add bedtools/2.18.0;
    sys echo something
}

and PRELOAD command should not appear in the task hint.
```

**Comment by pcingola** [comment]
OK, two separate problems:
  i) Naming the tasks in the cluster: I'm working on something, but it's not ready yet.

  ii) Removing some parts of task hint: This is currently not possible because task hint is taken directly from the 'sys' commands (i.e. first N characters from the sys commands). Task name was created for helping with this, I see you are already using it.

   iii) If you specify 'task( cpu:= 16 ) { ..." then everything inside the brackets is assumed to take 16 CPUs (i.e. 'modules.sh' and 'echo' commands)... I'm not sure why you say it is unexpected, but this is exactly the way it was supposed to work.

   iv) Writing 'modules' before each command sounds like a pain. Why don't you ask your admins if there is a simpler option (such as adding it to your profile script)?

I hope this helps.

**Comment by leepc12** [comment]
i) and ii) I see, thanks for this

iii) and iv), Yeah but if I add "module add MODULE-NAME or export PATH" to my ~/.profile or ~/.bashrc I cannot dynamically change program versions in BDS script. (using your nice function: string{} config(string fileName) ). 

My colleagues definitely want this feature... For example, people use bwa 0.7.7 by default using ~/.bashrc but sometimes their colleagues ask them to use different version of bwa for a specific experiment and they need to modify/source their .profile or .bashrc everytime they run BDS script.

**Comment by pcingola** [comment]
So, if I understand correctly, the problem is that the "modules.sh" appears in the task hint, right?
Doesn't "task name" somehow solve the problem? It does allow you to add whatever name you want...

Another option is to just show the whole command line instead of a 'task hint' (this is what I used at the beginning, but then the lines can be too long...(do you prefer this?).

**Comment by leepc12** [comment]
1) Please forget about task hint and modules.sh. 

What I really need is to efficiently control version of softwares (e.g. bwa, samtools and bedtools) in BDS script. I can define PATH for all jobs in BDS by adding the following line to bds.config:
```
clusterRunAdditionalArgs = -v PATH=...
```
This is actually not bad to control version. I choose softwares and add their paths to bds.config. However, in most cases, adding software bin path to env. var. PATH is not enough. People use "module add SOFTWARE/VERSION" (e.g. module add bwa/0.7.7") and all necessary environment variables are automatically added to bash shell.

So I think there should be something like the following:

pre {
	module add gatk/2.5.2
	module add bedtools/2.16.2
	module add bwa/0.7.7
	export PATH=$PATH:/python3/location/:.......
}

pre should be run on top of all task () jobs in BDS script so that all sys commands in task () can use PATH and other important env. var. defined in pre { }. I think this should be the best way to control software versions (dynamically) in BDS script. 

Or you can allow task ( ) to define "clusterRunAdditionalArgs" as parameter. Then clusterRunAdditionalArgs in bds.config is ignored and that in the task () parameter should be used for QSUB.
```
task( clusterRunAdditionalArgs := "-v PATH=software/bin/location: ..." ) {
}
```




2) I also want a report a bug. 

BDS didn't work if PATH=$HOME/.bds is not included in bds.config

```
$HOME/.bds -s sge test_sge.bds
```
```
sge.pe = shm
sge.mem = h_vmem
sge.timeout = h_rt
```
After adding the following line to bds.config . It worked.
```
clusterRunAdditionalArgs = -v PATH=$HOME/.bds
```
It is weird that BDS path should be included in job's environment var. PATH.

clusterRunAdditionalArgs = -v PATH=/home/leepc12/.bds:WHAT_EVER_PATH_I_WANT

**Comment by pcingola** [comment]
First isseu solved: Added config file parameter 'taskMaxHintLen' to control the number of char used in task's hint length (negative means unlimited).

**Comment by pcingola** [comment]
I'm not sure if the second issue is not a real issue since bds should be in 
your PATH (you usually set it in your .bashrc when you install the program). 
PATH and other environment variables should be propagated when you run 
cluster commands.

Issues iv can be solved using "string{} config(string fileName)" method to load 
your custom configuration for a given pipeline.

Let me know what you think, but if this is not solved, please re-open as separate 
issues so we can address each one properly.
